# main.yml
---
- name: Add target host to inventory
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml
  tasks:
    - name: Add target host
      add_host:
        name: "{{ opensupports_ip }}"
        ansible_user: "{{ opensupports_target_user }}"

- name: Run tasks on target host
  hosts: "{{ opensupports_ip }}"
  gather_facts: false
  vars_files:
    - vars/main.yml
  tasks:
    - include_tasks: tasks/main.yml
