- name: Create SSL certificate directories
  ansible.builtin.file:
    path: /etc/ssl/private
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Create a self-signed SSL certificate
  ansible.builtin.command:
    cmd: openssl req -new -newkey rsa:2048 -days 90 -nodes -x509 -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN={{ opensupports_ip }}" -keyout /etc/ssl/private/selfsigned.key -out /etc/ssl/certs/selfsigned.crt
  register: openssl_output
  ignore_errors: yes

- name: Create a configuration snippet for self-signed certificate
  ansible.builtin.copy:
    dest: /etc/httpd/conf.d/ssl-selfsigned.conf
    content: |
      LoadModule ssl_module modules/mod_ssl.so

      <VirtualHost *:443>
          DocumentRoot /var/www/html/opensupports
          <Directory /var/www/html/opensupports>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>
          ErrorLog /var/log/httpd/opensupports-error.log
          CustomLog /var/log/httpd/opensupports-access.log combined

          SSLEngine on
          SSLCertificateFile /etc/ssl/certs/selfsigned.crt
          SSLCertificateKeyFile /etc/ssl/private/selfsigned.key
      </VirtualHost>
    owner: root
    group: root
    mode: '0644'

- name: Create a cron job to renew the self-signed certificate every 3 months
  ansible.builtin.cron:
    name: "Renew self-signed SSL certificate"
    job: "openssl req -new -newkey rsa:2048 -days 90 -nodes -x509 -subj \"/C=US/ST=State/L=City/O=Organization/OU=Department/CN={{ opensupports_ip }}\" -keyout /etc/ssl/private/selfsigned.key -out /etc/ssl/certs/selfsigned.crt && systemctl restart httpd"
    month: "*/3"
    user: root

- name: Restart Apache to apply the new configuration
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Verify the SSL certificate using openssl
  ansible.builtin.command:
    cmd: openssl s_client -connect {{ opensupports_ip }}:443 -showcerts
  register: openssl_output

- name: Debug SSL certificate verification output
  debug:
    var: openssl_output.stdout