- name: Gather facts about the system
  ansible.builtin.setup:

- name: Show the distribution version
  debug:
    msg: "The distribution version is {{ ansible_distribution }} {{ ansible_distribution_version }}"